#!/bin/sh

# Load OpenFOAM v2.4
source /usr/local/module/spartan_old.sh
module load OpenFOAM/2.4.0-intel-2017.u2
source /usr/local/easybuild/software/OpenFOAM/2.4.0-intel-2017.u2/OpenFOAM-2.4.0/etc/bashrc

# Compile modified modules
for app in solutionControlx simpleControlx simpleFoamx
do
    cd $app
    wclean
    wmake
    cd ..
done

echo "The end."
